/**
 * functions/src/pipeline/seed.js
 * Popula a coleção /checklist_definitions no Firestore com todos os
 * elementos verificáveis do PPP, conforme Portaria SEEDF 139/2024
 * atualizada pela Portaria 174/2026.
 *
 * Executar uma única vez (ou ao atualizar a portaria):
 *   node src/pipeline/seed.js
 */

const { initializeApp, cert } = require('firebase-admin/app')
const { getFirestore, Timestamp } = require('firebase-admin/firestore')
const serviceAccount = require('../../serviceAccountKey.json')

initializeApp({ credential: cert(serviceAccount) })
const db = getFirestore()

// ─── Definição completa do checklist ─────────────────────────────────────────

const CHECKLIST = [

  // ══════════════════════════════════════════════════════════
  // BLOCO 1 — Pré-textuais  (Art. 9º, I)
  // ══════════════════════════════════════════════════════════
  {
    elementId:    'B1_1_capa',
    blockCode:    'B1',
    blockLabel:   'Pré-textuais',
    order:        1,
    label:        'Capa',
    description:  'Verificar presença da capa com identificação da escola, CRE, ano letivo e membros da equipe gestora/comissão.',
    normRef:      'Art. 9º, I, a — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   false,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['capa', 'coordenação regional', 'equipe gestora', 'comissão'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} possui capa com identificação completa da escola, CRE, ano letivo ({year}) e membros da equipe gestora ou comissão organizadora.',
  },
  {
    elementId:    'B1_2_sumario',
    blockCode:    'B1',
    blockLabel:   'Pré-textuais',
    order:        2,
    label:        'Sumário',
    description:  'Verificar presença de sumário com as seções do documento.',
    normRef:      'Art. 9º, I, b — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   false,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['sumário', 'sumario', 'índice'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} possui sumário com listagem das seções do documento.',
  },
  {
    elementId:    'B1_3_apresentacao',
    blockCode:    'B1',
    blockLabel:   'Pré-textuais',
    order:        3,
    label:        'Apresentação',
    description:  'Verificar presença de texto de apresentação contextualizando o PPP.',
    normRef:      'Art. 9º, I, c — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   false,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['apresentação', 'apresentacao'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} possui texto de apresentação que contextualiza o documento e a escola.',
  },

  // ══════════════════════════════════════════════════════════
  // BLOCO 2 — Identidade da Unidade Escolar  (Art. 9º, II, a-e)
  // ══════════════════════════════════════════════════════════
  {
    elementId:    'B2_1_historico',
    blockCode:    'B2',
    blockLabel:   'Identidade',
    order:        1,
    label:        'Histórico da unidade escolar',
    description:  'Deve incluir atos de regulação (criação, transformação, oferta, parcerias). Verificar se há datas, atos normativos e histórico de modalidades.',
    normRef:      'Art. 9º, II, a — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['histórico', 'historico', 'criação', 'ato de criação', 'regulação'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} contém histórico da unidade escolar com atos de regulação (criação, transformação, parcerias). O histórico deve ter datas, atos normativos e ser desenvolvido, não apenas um título.',
  },
  {
    elementId:    'B2_2_diagnostico',
    blockCode:    'B2',
    blockLabel:   'Identidade',
    order:        2,
    label:        'Diagnóstico da realidade',
    description:  'Deve conter dados quantitativos (matrículas, turmas, profissionais) e análise do contexto socioeconômico/territorial.',
    normRef:      'Art. 9º, II, b — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['diagnóstico', 'diagnostico', 'realidade', 'contexto', 'matrículas', 'turmas'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} contém diagnóstico da realidade com dados quantitativos (número de alunos, turmas, profissionais) e análise do contexto socioeconômico. Seções com menos de 200 palavras devem ser marcadas como atenção.',
  },
  {
    elementId:    'B2_3_funcao_social',
    blockCode:    'B2',
    blockLabel:   'Identidade',
    order:        3,
    label:        'Função social da escola',
    description:  'Declaração explícita da função social da escola.',
    normRef:      'Art. 9º, II, c — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['função social', 'funcao social', 'papel da escola'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} declara explicitamente a função social da escola. Deve ser um texto desenvolvido, não apenas o título da seção.',
  },
  {
    elementId:    'B2_4_missao',
    blockCode:    'B2',
    blockLabel:   'Identidade',
    order:        4,
    label:        'Missão da unidade escolar',
    description:  'Texto declarativo de missão presente e desenvolvido.',
    normRef:      'Art. 9º, II, d — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['missão', 'missao'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} contém declaração de missão desenvolvida. Uma única frase sem contextualização deve ser marcada como atenção.',
  },
  {
    elementId:    'B2_5_principios',
    blockCode:    'B2',
    blockLabel:   'Identidade',
    order:        5,
    label:        'Princípios orientadores da prática educativa',
    description:  'Lista ou texto com princípios explicitados.',
    normRef:      'Art. 9º, II, e — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['princípios', 'principios', 'valores', 'concepções'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} apresenta os princípios orientadores da prática educativa de forma desenvolvida, com ao menos 3 princípios explicitados.',
  },

  // ══════════════════════════════════════════════════════════
  // BLOCO 3 — Planejamento Pedagógico  (Art. 9º, II, f-j)
  // ══════════════════════════════════════════════════════════
  {
    elementId:    'B3_1_metas',
    blockCode:    'B3',
    blockLabel:   'Planejamento',
    order:        1,
    label:        'Metas da unidade escolar',
    description:  'Metas mensuráveis com referência ao PDE, PPA, PEI ou ODS 4.',
    normRef:      'Art. 9º, II, f — Portaria 139/2024',
    legalBasis:   [
      { norm: 'PDE 2015-2024', alias: 'Plano Distrital de Educação', required: false },
      { norm: 'PPA 2024-2027', alias: 'Plano Plurianual', required: false },
      { norm: 'ODS 4', alias: 'Objetivo de Desenvolvimento Sustentável 4', required: false },
    ],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['metas', 'meta', 'PDE', 'PPA', 'ODS'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} apresenta metas mensuráveis e se há referência ao PDE 2015-2024, PPA 2024-2027, PEI 2023-2027 ou ODS 4. Metas sem vinculação a políticas públicas devem ser marcadas como atenção.',
  },
  {
    elementId:    'B3_2_objetivos',
    blockCode:    'B3',
    blockLabel:   'Planejamento',
    order:        2,
    label:        'Objetivos geral e específicos',
    description:  'Objetivo geral + ao menos um objetivo específico.',
    normRef:      'Art. 9º, II, g — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['objetivo geral', 'objetivos específicos', 'objetivos especificos'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} apresenta objetivo geral e pelo menos um objetivo específico, ambos desenvolvidos.',
  },
  {
    elementId:    'B3_3_fundamentos',
    blockCode:    'B3',
    blockLabel:   'Planejamento',
    order:        3,
    label:        'Fundamentos teórico-metodológicos',
    description:  'Referências a autores ou correntes pedagógicas. Deve mencionar a BNCC.',
    normRef:      'Art. 9º, II, h — Portaria 139/2024',
    legalBasis:   [
      { norm: 'BNCC', alias: 'Base Nacional Comum Curricular', required: true },
    ],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['fundamentos', 'teórico', 'metodológico', 'BNCC', 'base nacional'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} apresenta fundamentos teórico-metodológicos com referências a autores ou correntes pedagógicas, e se menciona a BNCC (Base Nacional Comum Curricular). Ausência da BNCC deve ser marcada como crítico.',
  },
  {
    elementId:    'B3_4_org_curricular',
    blockCode:    'B3',
    blockLabel:   'Planejamento',
    order:        4,
    label:        'Organização curricular',
    description:  'Deve abordar: interdisciplinaridade, relação teoria-prática, temas transversais do Currículo em Movimento e programas/projetos da rede.',
    normRef:      'Art. 9º, II, i — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['organização curricular', 'curriculo', 'currículo', 'interdisciplinaridade', 'temas transversais'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} aborda a organização curricular contemplando: interdisciplinaridade, relação teoria-prática, temas transversais do Currículo em Movimento e programas/projetos da rede pública do DF.',
  },
  {
    elementId:    'B3_5_org_trabalho',
    blockCode:    'B3',
    blockLabel:   'Planejamento',
    order:        5,
    label:        'Organização do trabalho pedagógico',
    description:  'Organização dos tempos e espaços, relação escola-comunidade, metodologias de ensino, modalidades e etapas ofertadas.',
    normRef:      'Art. 9º, II, j — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['organização do trabalho', 'trabalho pedagógico', 'tempos e espaços', 'metodologias'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve a organização do trabalho pedagógico com: organização dos tempos e espaços, relação escola-comunidade, metodologias de ensino e modalidades/etapas ofertadas.',
  },

  // ══════════════════════════════════════════════════════════
  // BLOCO 4 — Ensino Médio  (Art. 9º, II, k — condicional)
  // ══════════════════════════════════════════════════════════
  {
    elementId:    'B4_1_itinerario',
    blockCode:    'B4',
    blockLabel:   'Ensino Médio',
    order:        1,
    label:        'Itinerário Formativo de Aprofundamento',
    description:  'Itinerário ofertado pela escola e unidades curriculares que o compõem.',
    normRef:      'Art. 9º, II, k, 1 — Portaria 174/2026',
    legalBasis:   [],
    isCritical:   true,
    isConditional: true,
    conditionKey: 'ensMedio',
    isNewIn2026:  false,
    searchKeywords: ['itinerário formativo', 'itinerario formativo', 'aprofundamento'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve o Itinerário Formativo de Aprofundamento ofertado, com as unidades curriculares que o compõem.',
  },
  {
    elementId:    'B4_2_percursos',
    blockCode:    'B4',
    blockLabel:   'Ensino Médio',
    order:        2,
    label:        'Percursos Educacionais Estruturados — estratégias de escolha',
    description:  'Estratégias para o processo de escolha dos Percursos pelos estudantes.',
    normRef:      'Art. 9º, II, k, 2 — Portaria 174/2026',
    legalBasis:   [],
    isCritical:   true,
    isConditional: true,
    conditionKey: 'ensMedio',
    isNewIn2026:  false,
    searchKeywords: ['percursos educacionais', 'percurso', 'escolha'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve as estratégias para o processo de escolha dos Percursos Educacionais Estruturados pelos estudantes.',
  },
  {
    elementId:    'B4_3_ifi',
    blockCode:    'B4',
    blockLabel:   'Ensino Médio',
    order:        3,
    label:        'Itinerário Formativo Integrador em Tempo Integral (IFI)',
    description:  'Organização do IFI: projetos pedagógicos de Matemática e Língua Portuguesa, Formação de Hábitos Individual e Social, unidades curriculares flexíveis.',
    normRef:      'Art. 9º, II, k, 3 — Portaria 174/2026',
    legalBasis:   [],
    isCritical:   true,
    isConditional: true,
    conditionKey: 'ensMedioTempoIntegral',
    isNewIn2026:  false,
    searchKeywords: ['IFI', 'itinerário formativo integrador', 'tempo integral', 'formação de hábitos'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve a organização do IFI (Itinerário Formativo Integrador em Tempo Integral) com: projetos de Matemática e Língua Portuguesa, Formação de Hábitos Individual e Social, e unidades curriculares flexíveis.',
  },

  // ══════════════════════════════════════════════════════════
  // BLOCO 5 — Programas e Projetos  (Art. 9º, II, l-n)
  // ══════════════════════════════════════════════════════════
  {
    elementId:    'B5_1_prog_institucionais',
    blockCode:    'B5',
    blockLabel:   'Projetos',
    order:        1,
    label:        'Programas e projetos institucionais da rede',
    description:  'Listagem dos programas institucionais desenvolvidos. Versões completas devem constar nos Apêndices.',
    normRef:      'Art. 9º, II, l — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   false,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['programas institucionais', 'projetos institucionais', 'programas da rede'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} lista os programas e projetos institucionais da rede SEEDF desenvolvidos na escola, e se menciona que as versões completas constam nos Apêndices.',
  },
  {
    elementId:    'B5_2A_proj_etnorracial',
    blockCode:    'B5',
    blockLabel:   'Projetos',
    order:        2,
    label:        'Projeto: educação para relações étnico-raciais e história afro-brasileira e indígena',
    description:  'OBRIGATÓRIO — Portaria 174/2026. Projeto voltado para a Educação para as Relações Étnico-Raciais e para o ensino de História e Cultura Afro-Brasileira e Indígena. Deve citar as Leis 10.639/2003 e 11.645/2008.',
    normRef:      'Art. 9º, II, m, 1 — Portaria 174/2026',
    legalBasis:   [
      { norm: 'Lei Federal 10.639/2003', alias: 'História e Cultura Afro-Brasileira', required: true },
      { norm: 'Lei Federal 11.645/2008', alias: 'História e Cultura Indígena', required: true },
      { norm: 'Lei 9.394/1996', alias: 'LDB', required: false },
    ],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  true,
    searchKeywords: ['étnico-racial', 'etnico-racial', 'afro-brasileira', 'indígena', 'lei 10.639', 'lei 11.645', '10639', '11645'],
    negativeKeywords: [],
    aiPromptTemplate: 'ELEMENTO CRÍTICO — NOVO EM 2026. Verifique se o PPP de {schoolName} contém projeto voltado para a Educação para as Relações Étnico-Raciais e ensino de História e Cultura Afro-Brasileira e Indígena. O projeto deve: (1) ser explicitamente descrito, não apenas mencionado; (2) citar a Lei 10.639/2003; (3) citar a Lei 11.645/2008. A ausência de qualquer desses itens deve ser marcada como crítico.',
  },
  {
    elementId:    'B5_2B_proj_maria_penha',
    blockCode:    'B5',
    blockLabel:   'Projetos',
    order:        3,
    label:        'Projeto: combate ao machismo e violências contra mulheres (Lei Maria da Penha)',
    description:  'OBRIGATÓRIO — Portaria 174/2026. Projeto voltado para o combate ao machismo e às violências contra mulheres. Deve abordar a Lei Maria da Penha de forma transversal em todas as etapas e modalidades. Deve citar a Lei 11.340/2006, a Lei Distrital 5.806/2017 e o Decreto 47.495/2025.',
    normRef:      'Art. 9º, II, m, 2 — Portaria 174/2026',
    legalBasis:   [
      { norm: 'Lei Federal 11.340/2006', alias: 'Lei Maria da Penha', required: true },
      { norm: 'Lei Distrital 5.806/2017', alias: 'Lei Distrital Maria da Penha nas Escolas', required: true },
      { norm: 'Decreto 47.495/2025', alias: 'Decreto GDF Maria da Penha nas Escolas', required: true },
    ],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  true,
    searchKeywords: ['maria da penha', 'machismo', 'violência contra', 'violência doméstica', 'lei 11.340', '11340', '5.806', 'decreto 47.495'],
    negativeKeywords: [],
    aiPromptTemplate: 'ELEMENTO CRÍTICO — NOVO EM 2026. Verifique se o PPP de {schoolName} contém projeto voltado para o combate ao machismo e violências contra mulheres. O projeto deve: (1) ser explicitamente descrito com ações pedagógicas, não apenas citado; (2) mencionar a Lei Maria da Penha (Lei 11.340/2006); (3) mencionar a Lei Distrital 5.806/2017; (4) mencionar o Decreto 47.495/2025; (5) indicar abordagem transversal em todas as etapas e modalidades. A ausência de qualquer desses itens deve ser marcada como crítico.',
  },
  {
    elementId:    'B5_3_proj_especificos',
    blockCode:    'B5',
    blockLabel:   'Projetos',
    order:        4,
    label:        'Projetos específicos da escola',
    description:  'Projetos da escola com vinculação a eixos transversais do Currículo em Movimento e metas do PDE/PPA/PEI/ODS 4.',
    normRef:      'Art. 9º, II, m — Portaria 174/2026',
    legalBasis:   [],
    isCritical:   false,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['projetos específicos', 'projetos especificos', 'eixos transversais', 'currículo em movimento'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} apresenta projetos específicos da escola com indicação dos eixos transversais do Currículo em Movimento mobilizados, e vinculação a metas do PDE, PPA, PEI ou ODS 4.',
  },
  {
    elementId:    'B5_4_parcerias',
    blockCode:    'B5',
    blockLabel:   'Projetos',
    order:        5,
    label:        'Projetos em parceria com instituições externas',
    description:  'Parcerias com outras instituições, órgãos do governo ou OSC, com indicação de eixos transversais e metas.',
    normRef:      'Art. 9º, II, n — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   false,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['parceria', 'parcerias', 'organizações da sociedade civil', 'OSC'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve projetos em parceria com outras instituições ou órgãos, com identificação dos parceiros e vinculação a eixos transversais.',
  },

  // ══════════════════════════════════════════════════════════
  // BLOCO 6 — Avaliação e Suporte  (Art. 9º, II, o-r)
  // ══════════════════════════════════════════════════════════
  {
    elementId:    'B6_1_avaliacao',
    blockCode:    'B6',
    blockLabel:   'Avaliação',
    order:        1,
    label:        'Processo avaliativo',
    description:  'Deve mencionar os 3 níveis (sala de aula, larga escala, institucional), as funções (formativa, somativa, diagnóstica) e o papel do Conselho de Classe.',
    normRef:      'Art. 9º, II, o — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['processo avaliativo', 'avaliação formativa', 'avaliação somativa', 'avaliação diagnóstica', 'conselho de classe', 'avaliação em larga escala'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve o processo avaliativo contemplando: (1) os 3 níveis de avaliação (sala de aula, larga escala, institucional); (2) as funções formativa, somativa e diagnóstica; (3) o papel do Conselho de Classe.',
  },
  {
    elementId:    'B6_2_seaa',
    blockCode:    'B6',
    blockLabel:   'Avaliação',
    order:        2,
    label:        'Atuação do SEAA',
    description:  'Seção dedicada ao Serviço Especializado de Apoio à Aprendizagem.',
    normRef:      'Art. 9º, II, p — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['SEAA', 'serviço especializado de apoio', 'apoio à aprendizagem'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve a atuação do SEAA (Serviço Especializado de Apoio à Aprendizagem) de forma desenvolvida.',
  },
  {
    elementId:    'B6_3_oe',
    blockCode:    'B6',
    blockLabel:   'Avaliação',
    order:        3,
    label:        'Atuação da Orientação Educacional (OE)',
    description:  'Seção dedicada à Orientação Educacional.',
    normRef:      'Art. 9º, II, q — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['orientação educacional', 'orientacao educacional', 'OE'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve a atuação da Orientação Educacional (OE) de forma desenvolvida.',
  },
  {
    elementId:    'B6_4_aee',
    blockCode:    'B6',
    blockLabel:   'Avaliação',
    order:        4,
    label:        'Atuação do AEE / Sala de Recursos',
    description:  'Seção dedicada ao Atendimento Educacional Especializado.',
    normRef:      'Art. 9º, II, r — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['AEE', 'atendimento educacional especializado', 'sala de recursos'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve a atuação do AEE (Atendimento Educacional Especializado / Sala de Recursos) de forma desenvolvida.',
  },

  // ══════════════════════════════════════════════════════════
  // BLOCO 7 — Profissionais e Estruturas  (Art. 9º, II, s-w)
  // ══════════════════════════════════════════════════════════
  {
    elementId:    'B7_1_apoio_escolar',
    blockCode:    'B7',
    blockLabel:   'Profissionais',
    order:        1,
    label:        'Profissionais de apoio escolar',
    description:  'Monitor, Educador Social Voluntário, Jovem Candango e outros.',
    normRef:      'Art. 9º, II, s — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   false,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['monitor', 'educador social voluntário', 'jovem candango', 'apoio escolar'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve a atuação dos profissionais de apoio escolar (Monitor, Educador Social Voluntário, Jovem Candango).',
  },
  {
    elementId:    'B7_2_biblioteca',
    blockCode:    'B7',
    blockLabel:   'Profissionais',
    order:        2,
    label:        'Biblioteca escolar como espaço de aprendizagem',
    description:  'Papel da biblioteca e atuação do profissional que nela atua.',
    normRef:      'Art. 9º, II, t — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   false,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['biblioteca', 'biblioteca escolar'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve o papel da biblioteca escolar como espaço de aprendizagem e a atuação do profissional bibliotecário.',
  },
  {
    elementId:    'B7_3_conselho_escolar',
    blockCode:    'B7',
    blockLabel:   'Profissionais',
    order:        3,
    label:        'Papel e atuação do Conselho Escolar',
    description:  'Descrição do papel e atuação do Conselho Escolar.',
    normRef:      'Art. 9º, II, u — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['conselho escolar'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve o papel e a atuação do Conselho Escolar de forma desenvolvida.',
  },
  {
    elementId:    'B7_4_readaptados',
    blockCode:    'B7',
    blockLabel:   'Profissionais',
    order:        4,
    label:        'Papel e atuação dos profissionais readaptados',
    description:  'Descrição do papel dos profissionais readaptados.',
    normRef:      'Art. 9º, II, v — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   false,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['readaptados', 'readaptado', 'servidor readaptado'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve o papel e a atuação dos profissionais readaptados.',
  },
  {
    elementId:    'B7_5_coord_pedagogica',
    blockCode:    'B7',
    blockLabel:   'Profissionais',
    order:        5,
    label:        'Coordenação pedagógica — papel, desenvolvimento e formação continuada',
    description:  'Três subitens obrigatórios: (1) papel do coordenador pedagógico; (2) desenvolvimento da coordenação pedagógica; (3) valorização e formação continuada.',
    normRef:      'Art. 9º, II, w — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['coordenação pedagógica', 'coordenador pedagógico', 'formação continuada'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve a coordenação pedagógica contemplando os três subitens obrigatórios: (1) papel do coordenador pedagógico; (2) desenvolvimento da coordenação pedagógica; (3) valorização e formação continuada dos profissionais.',
  },

  // ══════════════════════════════════════════════════════════
  // BLOCO 8 — Gestão e Estratégias  (Art. 9º, II, x-z)
  // ══════════════════════════════════════════════════════════
  {
    elementId:    'B8_1_permanencia',
    blockCode:    'B8',
    blockLabel:   'Gestão',
    order:        1,
    label:        'Estratégias de permanência, fluxo e recomposição',
    description:  'Estratégias para: redução de abandono/evasão/reprovação, recomposição das aprendizagens, cultura de paz, transição escolar e Gestão Compartilhada.',
    normRef:      'Art. 9º, II, x — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['abandono', 'evasão', 'reprovação', 'permanência', 'recomposição', 'cultura de paz', 'gestão compartilhada'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} apresenta estratégias para: (1) redução de abandono, evasão e reprovação; (2) recomposição das aprendizagens; (3) cultura de paz; (4) transição escolar; (5) Gestão Compartilhada.',
  },
  {
    elementId:    'B8_2_implementacao',
    blockCode:    'B8',
    blockLabel:   'Gestão',
    order:        2,
    label:        'Processo de implementação do PPP — 6 dimensões da gestão',
    description:  'Deve contemplar as 6 dimensões: Pedagógica, de Resultados Educacionais, Participativa, de Pessoas, Financeira e Administrativa.',
    normRef:      'Art. 9º, II, y — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['implementação do ppp', 'gestão pedagógica', 'gestão participativa', 'gestão financeira', 'gestão administrativa', 'gestão de pessoas'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve o processo de implementação contemplando as 6 dimensões da gestão escolar: (1) Pedagógica; (2) de Resultados Educacionais; (3) Participativa; (4) de Pessoas; (5) Financeira; (6) Administrativa.',
  },
  {
    elementId:    'B8_3_monitoramento',
    blockCode:    'B8',
    blockLabel:   'Gestão',
    order:        3,
    label:        'Acompanhamento, monitoramento e avaliação do PPP',
    description:  'Avaliação coletiva, periodicidade definida, procedimentos/instrumentos e registros.',
    normRef:      'Art. 9º, II, z — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   true,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['monitoramento', 'acompanhamento do ppp', 'avaliação do ppp', 'periodicidade'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} descreve o processo de acompanhamento, monitoramento e avaliação do PPP, com: avaliação coletiva, periodicidade definida, procedimentos/instrumentos e registros.',
  },

  // ══════════════════════════════════════════════════════════
  // BLOCO 9 — Pós-textuais  (Art. 9º, III)
  // ══════════════════════════════════════════════════════════
  {
    elementId:    'B9_1_referencias',
    blockCode:    'B9',
    blockLabel:   'Pós-textuais',
    order:        1,
    label:        'Referências bibliográficas',
    description:  'Lista de referências presente e com os normativos obrigatórios citados: LDB, BNCC, PDE, PPA, PEI.',
    normRef:      'Art. 9º, III, a — Portaria 139/2024',
    legalBasis:   [
      { norm: 'Lei 9.394/1996', alias: 'LDB', required: true },
      { norm: 'BNCC', alias: 'Base Nacional Comum Curricular', required: true },
      { norm: 'PDE 2015-2024', alias: 'Plano Distrital de Educação', required: false },
      { norm: 'PPA 2024-2027', alias: 'Plano Plurianual', required: false },
    ],
    isCritical:   false,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['referências', 'referencias', 'referências bibliográficas'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} possui referências bibliográficas e se os normativos obrigatórios estão citados: LDB (Lei 9.394/1996), BNCC. Verifique também se há menção ao PDE 2015-2024 e PPA 2024-2027.',
  },
  {
    elementId:    'B9_2_apendices',
    blockCode:    'B9',
    blockLabel:   'Pós-textuais',
    order:        2,
    label:        'Apêndices — planos de ação e projetos completos',
    description:  'Planos de ação, projetos e programas anuais completos. Verificar cruzamento: projetos mencionados no corpo devem estar nos apêndices.',
    normRef:      'Art. 9º, III, b — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   false,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['apêndices', 'apendices', 'apêndice', 'plano de ação'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} possui apêndices com planos de ação e projetos completos. Verifique se os projetos mencionados no corpo do documento (especialmente os obrigatórios) estão detalhados nos apêndices.',
  },
  {
    elementId:    'B9_3_anexos',
    blockCode:    'B9',
    blockLabel:   'Pós-textuais',
    order:        3,
    label:        'Anexos',
    description:  'Documentos elaborados por terceiros para complementar o PPP.',
    normRef:      'Art. 9º, III, c — Portaria 139/2024',
    legalBasis:   [],
    isCritical:   false,
    isConditional: false,
    conditionKey: null,
    isNewIn2026:  false,
    searchKeywords: ['anexos', 'anexo'],
    negativeKeywords: [],
    aiPromptTemplate: 'Verifique se o PPP de {schoolName} possui seção de anexos com documentos de terceiros.',
  },
]

// ─── Script de seed ───────────────────────────────────────────────────────────

async function seed() {
  console.log(`Iniciando seed de ${CHECKLIST.length} elementos...`)

  const batch = db.batch()

  for (const el of CHECKLIST) {
    const ref = db.collection('checklist_definitions').doc(el.elementId)
    batch.set(ref, {
      ...el,
      active:    true,
      createdAt: Timestamp.now(),
      updatedAt: Timestamp.now(),
    })
  }

  await batch.commit()
  console.log(`✅ ${CHECKLIST.length} elementos gravados em /checklist_definitions`)

  // Resumo por bloco
  const blocks = {}
  for (const el of CHECKLIST) {
    if (!blocks[el.blockCode]) blocks[el.blockCode] = { total: 0, critical: 0, new2026: 0 }
    blocks[el.blockCode].total++
    if (el.isCritical)  blocks[el.blockCode].critical++
    if (el.isNewIn2026) blocks[el.blockCode].new2026++
  }
  console.table(blocks)
}

seed().catch(err => { console.error(err); process.exit(1) })

module.exports = { CHECKLIST }
